/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jenaPackage;

import ClassPackage.TableContent;
import com.hp.hpl.jena.query.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rhyzard
 */
public class CalificacionForm extends javax.swing.JFrame {

    /**
     * Creates new form CalificacionForm
     */
    public TableContent tc = new TableContent(); 
    public ArrayList<String> ListActivite = new ArrayList<String>();
    public CalificacionForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnpAspirante = new javax.swing.JButton();
        BtnpPuntuacionMayor = new javax.swing.JButton();
        BtnpPuntuacionMenor = new javax.swing.JButton();
        BtnpVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Calificación");

        BtnpAspirante.setText("Por Aspirantes");
        BtnpAspirante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpAspiranteActionPerformed(evt);
            }
        });

        BtnpPuntuacionMayor.setText("Por Puntuación Mayor");
        BtnpPuntuacionMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpPuntuacionMayorActionPerformed(evt);
            }
        });

        BtnpPuntuacionMenor.setText("Por Puntuación Menor");
        BtnpPuntuacionMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpPuntuacionMenorActionPerformed(evt);
            }
        });

        BtnpVolver.setForeground(new java.awt.Color(255, 0, 0));
        BtnpVolver.setText("Volver");
        BtnpVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnpVolverMouseClicked(evt);
            }
        });
        BtnpVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpVolverActionPerformed(evt);
            }
        });

        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(DataTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(106, 106, 106)
                                .addComponent(BtnpAspirante, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnpPuntuacionMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnpPuntuacionMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnpVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BtnpAspirante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnpPuntuacionMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnpPuntuacionMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(BtnpVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnpPuntuacionMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpPuntuacionMayorActionPerformed
        // TODO add your handling code here:
        try{
            String[] tableColumnsName = {"Aspirantes","Resultados"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            String queryString = 
                         "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                         + "SELECT ?Aspirantes ?Resultado \n"
                         + "WHERE { ?pum ont:obtiene_un ?are. \n"
                         + "?pum ont:nombre ?Aspirantes.\n"
                         + "?are ont:calificacion ?Resultado. \n"
                         + "FILTER(?Resultado >= 160).}"; 
            ResultSet re = OpenOWL.ExecSparQl(queryString);
            tc.ConstructionTable(re,"Aspirantes","Resultado",aModel,DataTable );
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BtnpPuntuacionMayorActionPerformed

    private void BtnpPuntuacionMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpPuntuacionMenorActionPerformed
        // TODO add your handling code here:
        try{
            String[] tableColumnsName = {"Aspirantes","Resultados"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            String queryString = 
                         "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                         + "SELECT ?Aspirantes ?Resultado \n"
                         + "WHERE { ?pum ont:obtiene_un ?are. \n"
                         + "?pum ont:nombre ?Aspirantes.\n"
                         + "?are ont:calificacion ?Resultado. \n"
                         + "FILTER(?Resultado < 160).}"; 
            ResultSet re = OpenOWL.ExecSparQl(queryString);
            tc.ConstructionTable(re,"Aspirantes","Resultado",aModel,DataTable );
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BtnpPuntuacionMenorActionPerformed

    private void BtnpVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnpVolverActionPerformed

    private void BtnpVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnpVolverMouseClicked
        // TODO add your handling code here:
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnpVolverMouseClicked

    private void BtnpAspiranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpAspiranteActionPerformed
        // TODO add your handling code here:
        try{
            String[] tableColumnsName = {"Aspirantes","Resultados"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            String queryString = 
                         "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                         + "SELECT ?Aspirantes ?Resultado \n"
                         + "WHERE { ?pum ont:obtiene_un ?are. \n"
                         + "?pum ont:nombre ?Aspirantes.\n"
                         + "?are ont:calificacion ?Resultado.}"; 
            ResultSet re = OpenOWL.ExecSparQl(queryString);
            tc.ConstructionTable(re,"Aspirantes","Resultado",aModel,DataTable );
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BtnpAspiranteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalificacionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalificacionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalificacionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalificacionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalificacionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnpAspirante;
    private javax.swing.JButton BtnpPuntuacionMayor;
    private javax.swing.JButton BtnpPuntuacionMenor;
    private javax.swing.JButton BtnpVolver;
    private javax.swing.JTable DataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
