/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jenaPackage;

import ClassPackage.TableContent;
import com.hp.hpl.jena.query.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rhyzard
 */
public class CarreraForm extends javax.swing.JFrame {

    /**
     * Creates new form CarreraForm
     */
    public TableContent tc = new TableContent(); 
    public ArrayList<String> ListActivite = new ArrayList<String>();
    
    public CarreraForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnpUniversidad = new javax.swing.JButton();
        btnpEstudiante = new javax.swing.JButton();
        btnpUbicacion = new javax.swing.JButton();
        BtnpVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();
        comboCarreras = new javax.swing.JComboBox<>();
        btnpCalificacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Carreras");

        btnpUniversidad.setForeground(new java.awt.Color(102, 102, 0));
        btnpUniversidad.setText("Por Universidad");
        btnpUniversidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpUniversidadActionPerformed(evt);
            }
        });

        btnpEstudiante.setForeground(new java.awt.Color(102, 102, 0));
        btnpEstudiante.setText("Por Estudiante");
        btnpEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpEstudianteActionPerformed(evt);
            }
        });

        btnpUbicacion.setForeground(new java.awt.Color(102, 102, 0));
        btnpUbicacion.setText("Por Ubicación");
        btnpUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpUbicacionActionPerformed(evt);
            }
        });

        BtnpVolver.setForeground(new java.awt.Color(255, 0, 0));
        BtnpVolver.setText("Volver");
        BtnpVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnpVolverMouseClicked(evt);
            }
        });
        BtnpVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpVolverActionPerformed(evt);
            }
        });

        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(DataTable);

        comboCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Catolica", "Central", "ESPE" }));
        comboCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCarrerasActionPerformed(evt);
            }
        });

        btnpCalificacion.setForeground(new java.awt.Color(102, 102, 0));
        btnpCalificacion.setText("Por Calificación");
        btnpCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpCalificacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnpCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnpUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnpUbicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BtnpVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnpEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(comboCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpUniversidad)
                    .addComponent(btnpUbicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpEstudiante)
                    .addComponent(btnpCalificacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(BtnpVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnpVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnpVolverActionPerformed

    private void BtnpVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnpVolverMouseClicked
        // TODO add your handling code here:
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnpVolverMouseClicked

    private void btnpUniversidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpUniversidadActionPerformed
        // TODO add your handling code here:
        try{
            String[] tableColumnsName = {"Universidad","Carreras"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            String queryString = 
                         "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                         + "SELECT ?Universidad ?tieneCarreras \n"
                         + "WHERE { ?pum ont:tieneCarreras ?are. \n"
                         + "?pum ont:nombre ?Universidad.\n"
                         + "?are ont:nombre ?tieneCarreras.}"; 
            ResultSet re = OpenOWL.ExecSparQl(queryString);
            tc.ConstructionTable(re,"Universidad","tieneCarreras",aModel,DataTable );
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnpUniversidadActionPerformed

    private void btnpUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpUbicacionActionPerformed
        // TODO add your handling code here:
        try{
            String[] tableColumnsName = {"Carreras","Ubicación"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            String queryString = 
                         "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                         + "SELECT ?Carreras ?Universidad \n"
                         + "WHERE { ?pum ont:tieneCarreras ?are. \n"
                         + "?pum ont:ciudad ?Universidad.\n"
                         + "?are ont:nombre ?Carreras.}"; 
            ResultSet re = OpenOWL.ExecSparQl(queryString);
            tc.ConstructionTable(re,"Carreras","Universidad",aModel,DataTable );
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnpUbicacionActionPerformed

    private void btnpEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpEstudianteActionPerformed
        // TODO add your handling code here:
        try{
            String[] tableColumnsName = {"Carreras","Estudiantes"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            String queryString = 
                         "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                         + "SELECT ?Carreras ?elegidas_por \n"
                         + "WHERE { ?pum ont:elegidas_por ?are. \n"
                         + "?pum ont:nombre ?Carreras.\n"
                         + "?are ont:nombre ?elegidas_por.}"; 
            ResultSet re = OpenOWL.ExecSparQl(queryString);
            tc.ConstructionTable(re,"Carreras","elegidas_por",aModel,DataTable );
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnpEstudianteActionPerformed

    private void comboCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCarrerasActionPerformed
        // TODO add your handling code here:
        try{
            String uni = comboCarreras.getSelectedItem().toString();
            //System.out.println(uni);
            String[] tableColumnsName = {"ID","Carreras"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            switch (uni) 
            {
                case "Central":                 
                        String queryString = 
                                     "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                                     + "SELECT ?Carreras ?Universidad \n"
                                     + "WHERE { ?pum ont:esta_en ?are. \n"
                                     + "?pum ont:nombre ?Carreras.\n"
                                     + "?are ont:id ?Universidad. \n"
                                     + "FILTER(?Universidad = 2)}";
                        ResultSet re = OpenOWL.ExecSparQl(queryString);
                        tc.ConstructionTable(re,"Universidad","Carreras",aModel,DataTable );
                        break;
                case "Catolica":
                        String queryString1 = 
                                     "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                                     + "SELECT ?Carreras ?Universidad \n"
                                     + "WHERE { ?pum ont:esta_en ?are. \n"
                                     + "?pum ont:nombre ?Carreras.\n"
                                     + "?are ont:id ?Universidad. \n"
                                     + "FILTER(?Universidad = 3)}";
                        ResultSet re1 = OpenOWL.ExecSparQl(queryString1);
                        tc.ConstructionTable(re1,"Universidad","Carreras",aModel,DataTable );
                        break;
                case "ESPE":
                        String queryString2 = 
                                     "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                                     + "SELECT ?Carreras ?Universidad \n"
                                     + "WHERE { ?pum ont:esta_en ?are. \n"
                                     + "?pum ont:nombre ?Carreras.\n"
                                     + "?are ont:id ?Universidad. \n"
                                     + "FILTER(?Universidad = 1)}";
                        ResultSet re2 = OpenOWL.ExecSparQl(queryString2);
                        tc.ConstructionTable(re2,"Universidad","Carreras",aModel,DataTable );
                        break;    

                default: System.out.println("Selecciona una Universidad");;
                         break;
            }
            
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_comboCarrerasActionPerformed

    private void btnpCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpCalificacionActionPerformed
        // TODO add your handling code here:
        try{
            String[] tableColumnsName = {"Carreras","Puntaje de Ingreso"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            String queryString = 
                         "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                         + "SELECT ?Carreras ?Resultado \n"
                         + "WHERE { ?pum ont:Punt_aprobacion ?are. \n"
                         + "?pum ont:nombre ?Carreras.\n"
                         + "?are ont:calificacion ?Resultado.}"; 
            ResultSet re = OpenOWL.ExecSparQl(queryString);
            tc.ConstructionTable(re,"Carreras","Resultado",aModel,DataTable );
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnpCalificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarreraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarreraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarreraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarreraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarreraForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnpVolver;
    private javax.swing.JTable DataTable;
    private javax.swing.JButton btnpCalificacion;
    private javax.swing.JButton btnpEstudiante;
    private javax.swing.JButton btnpUbicacion;
    private javax.swing.JButton btnpUniversidad;
    private javax.swing.JComboBox<String> comboCarreras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
