/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jenaPackage;

import ClassPackage.TableContent;
import com.hp.hpl.jena.query.QuerySolution;
import com.hp.hpl.jena.query.ResultSet;
import com.hp.hpl.jena.rdf.model.RDFNode;
import java.awt.Color;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.util.ArrayList;
import javax.print.attribute.AttributeSet;
import javax.swing.JTable;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;


/**
 *
 * @author Rhyzard
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public TableContent tc = new TableContent(); 
    public ArrayList<String> ListActivite = new ArrayList<String>();
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPostulacion = new javax.swing.JButton();
        btnCarreras = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        btnTipoIngreso = new javax.swing.JButton();
        BtnCalificacion = new javax.swing.JButton();
        btnExamen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Información Postulaciones");

        btnPostulacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPostulacion.setForeground(new java.awt.Color(255, 0, 0));
        btnPostulacion.setText("Postulación");
        btnPostulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostulacionActionPerformed(evt);
            }
        });

        btnCarreras.setForeground(new java.awt.Color(204, 204, 0));
        btnCarreras.setText("Carreras");
        btnCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarrerasMouseClicked(evt);
            }
        });

        btnResultados.setForeground(new java.awt.Color(0, 102, 204));
        btnResultados.setText("Resultados");
        btnResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResultadosMouseClicked(evt);
            }
        });

        btnTipoIngreso.setForeground(new java.awt.Color(0, 204, 0));
        btnTipoIngreso.setText("Tipo de Ingreso");
        btnTipoIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTipoIngresoMouseClicked(evt);
            }
        });

        BtnCalificacion.setForeground(new java.awt.Color(102, 102, 102));
        BtnCalificacion.setText("Calificación");
        BtnCalificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCalificacionMouseClicked(evt);
            }
        });

        btnExamen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExamen.setForeground(new java.awt.Color(255, 0, 0));
        btnExamen.setText("Examen");
        btnExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamenActionPerformed(evt);
            }
        });

        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(DataTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTipoIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCalificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPostulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                .addComponent(btnCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPostulacion)
                    .addComponent(btnCarreras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResultados)
                    .addComponent(btnExamen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTipoIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCalificacion)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPostulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostulacionActionPerformed
        // TODO add your handling code here:
        try{
          String[] tableColumnsName = {"Apirantes","Postulación"}; 
          DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
          aModel.setColumnIdentifiers(tableColumnsName);
          aModel.setRowCount(0);
          String queryString = 
                         "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                         + "SELECT ?Aspirantes ?Postulacion \n"
                         + "WHERE { ?oso ont:gana_una ?are. \n"
                         + "?oso ont:nombre ?Aspirantes.\n"
                         + "?are ont:periodo ?Postulacion.}"; 
          //  String s = go.toString();
            ResultSet re = OpenOWL.ExecSparQl(queryString);
            tc.ConstructionTable(re,"Aspirantes","Postulacion",aModel,DataTable );
            //Datos hechos
            //String s = OpenOWL.GetResultAsString(queryString); //call method GetResultAsString from OpenOWL class
          // test ;)   
            //System.out.println(s);
 
          // display it .. 
           //appendVersPane(TxtPane, s, Color.DARK_GRAY);
        
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnPostulacionActionPerformed

    private void btnExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamenActionPerformed
        // TODO add your handling code here:
        try{
            String[] tableColumnsName = {"Examen","Aspirantes"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            String queryString = 
                         "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                         + "SELECT ?Examen ?es_rendido_por \n"
                         + "WHERE { ?oso ont:es_rendido_por ?are. \n"
                         + "?oso ont:nombre ?Examen.\n"
                         + "?are ont:nombre ?es_rendido_por.}"; 
            ResultSet re = OpenOWL.ExecSparQl(queryString);
            tc.ConstructionTable(re,"Examen","es_rendido_por",aModel,DataTable );
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnExamenActionPerformed

    private void btnCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarrerasMouseClicked
        // TODO add your handling code here:
        CarreraForm carr = new CarreraForm();
        carr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCarrerasMouseClicked

    private void btnResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResultadosMouseClicked
        // TODO add your handling code here:
        ResultadosForm re= new ResultadosForm();
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnResultadosMouseClicked

    private void btnTipoIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTipoIngresoMouseClicked
        // TODO add your handling code here:
        TIngresoForm tingreso = new TIngresoForm();
        tingreso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTipoIngresoMouseClicked

    private void BtnCalificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCalificacionMouseClicked
        // TODO add your handling code here:
        CalificacionForm cal = new CalificacionForm();
        cal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCalificacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalificacion;
    private javax.swing.JTable DataTable;
    private javax.swing.JButton btnCarreras;
    private javax.swing.JButton btnExamen;
    private javax.swing.JButton btnPostulacion;
    private javax.swing.JButton btnResultados;
    private javax.swing.JButton btnTipoIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
  private void appendVersPane(JTextPane tp, String msg, Color c)
    {
        StyleContext sc = StyleContext.getDefaultStyleContext();
        javax.swing.text.AttributeSet aset = sc.addAttribute(SimpleAttributeSet.EMPTY, StyleConstants.Foreground, c);

        aset = sc.addAttribute(aset, StyleConstants.FontFamily, "Lucida Console");
        aset = sc.addAttribute(aset, StyleConstants.Alignment, StyleConstants.ALIGN_JUSTIFIED);

        int len = tp.getDocument().getLength();
        tp.setCaretPosition(len);
        tp.setCharacterAttributes(aset, false);
        tp.replaceSelection(msg);
    }
}
