/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jenaPackage;

import ClassPackage.TableContent;
import com.hp.hpl.jena.query.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rhyzard
 */
public class ResultadosForm extends javax.swing.JFrame {

    /**
     * Creates new form ResultadosForm
     */
    public TableContent tc = new TableContent(); 
    public ArrayList<String> ListActivite = new ArrayList<String>();
    public ResultadosForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUniSelect = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnpVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();
        comboAprobados = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUniSelect.setForeground(new java.awt.Color(0, 102, 204));
        btnUniSelect.setText("Universidad Seleccionada");
        btnUniSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUniSelectActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Resultados");

        BtnpVolver.setForeground(new java.awt.Color(255, 0, 0));
        BtnpVolver.setText("Volver");
        BtnpVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnpVolverMouseClicked(evt);
            }
        });

        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(DataTable);

        comboAprobados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprobados", "Reprobados" }));
        comboAprobados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAprobadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnpVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUniSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(comboAprobados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnUniSelect))
                .addGap(18, 18, 18)
                .addComponent(comboAprobados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnpVolver)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnpVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnpVolverMouseClicked
        // TODO add your handling code here:
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnpVolverMouseClicked

    private void comboAprobadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAprobadosActionPerformed
        // TODO add your handling code here:
        try{
            String uni = comboAprobados.getSelectedItem().toString();
            //System.out.println(uni);
            String[] tableColumnsName = {"Postulacion","Aspirantes"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            switch (uni) 
            {
                case "Aprobados":                 
                        String queryString = 
                                     "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                                     + "SELECT ?Aspirantes ?Postulacion \n"
                                     + "WHERE { ?pum ont:gana_una ?are. \n"
                                     + "?pum ont:nombre ?Aspirantes.\n"
                                     + "?are ont:id ?Postulacion. \n"
                                     + "FILTER(?Postulacion = 1)}";
                        ResultSet re = OpenOWL.ExecSparQl(queryString);
                        tc.ConstructionTable(re,"Aspirantes","Postulacion",aModel,DataTable );
                        break;
                case "Reprobados":
                        String queryString1 = 
                                     "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                                     + "SELECT ?Aspirantes ?Postulacion \n"
                                     + "WHERE { ?pum ont:gana_una ?are. \n"
                                     + "?pum ont:nombre ?Aspirantes.\n"
                                     + "?are ont:id ?Postulacion. \n"
                                     + "FILTER(?Postulacion = 2)}";
                        ResultSet re1 = OpenOWL.ExecSparQl(queryString1);
                        tc.ConstructionTable(re1,"Aspirantes","Postulacion",aModel,DataTable );
                        break;
                
                default: System.out.println("Selecciona un dato");;
                         break;
            }
            
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_comboAprobadosActionPerformed

    private void btnUniSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUniSelectActionPerformed
        // TODO add your handling code here:
        try{
            String[] tableColumnsName = {"Universidad","Aspirantes"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            String queryString = 
                         "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                         + "SELECT ?Aspirantes ?Universidad \n"
                         + "WHERE { ?pum ont:ingresen_a ?are. \n"
                         + "?pum ont:nombre ?Universidad.\n"
                         + "?are ont:nombre ?Aspirantes.}"; 
            ResultSet re = OpenOWL.ExecSparQl(queryString);
            tc.ConstructionTable(re,"Aspirantes","Universidad",aModel,DataTable );
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnUniSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultadosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnpVolver;
    private javax.swing.JTable DataTable;
    private javax.swing.JButton btnUniSelect;
    private javax.swing.JComboBox<String> comboAprobados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
