/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jenaPackage;

import ClassPackage.TableContent;
import com.hp.hpl.jena.query.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rhyzard
 */
public class TIngresoForm extends javax.swing.JFrame {

    /**
     * Creates new form TIngresoForm
     */
    public TableContent tc = new TableContent(); 
    public ArrayList<String> ListActivite = new ArrayList<String>();
    public TIngresoForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTipoIngreso = new javax.swing.JButton();
        BtnpVolver = new javax.swing.JButton();
        comboINgreso = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Tipo de Ingreso");

        btnTipoIngreso.setForeground(new java.awt.Color(0, 204, 0));
        btnTipoIngreso.setText("Ingreso General");
        btnTipoIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoIngresoActionPerformed(evt);
            }
        });

        BtnpVolver.setForeground(new java.awt.Color(255, 0, 0));
        BtnpVolver.setText("Volver");
        BtnpVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnpVolverMouseClicked(evt);
            }
        });

        comboINgreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intensivo", "Regular", "Directo" }));
        comboINgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboINgresoActionPerformed(evt);
            }
        });

        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(DataTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboINgreso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addComponent(btnTipoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnpVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnTipoIngreso))
                .addGap(21, 21, 21)
                .addComponent(comboINgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnpVolver)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnpVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnpVolverMouseClicked
        // TODO add your handling code here:
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnpVolverMouseClicked

    private void comboINgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboINgresoActionPerformed
        // TODO add your handling code here:
        try{
            String uni = comboINgreso.getSelectedItem().toString();
            //System.out.println(uni);
            String[] tableColumnsName = {"Ingreso","Aspirantes"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            switch (uni) 
            {
                case "Directo":                 
                        String queryString = 
                                     "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                                     + "SELECT ?Ingreso ?Aspirantes \n"
                                     + "WHERE { ?pum ont:ingresan_por ?are. \n"
                                     + "?pum ont:nombre ?Aspirantes.\n"
                                     + "?are ont:id ?Ingreso. \n"
                                     + "FILTER(?Ingreso = 1)}";
                        ResultSet re = OpenOWL.ExecSparQl(queryString);
                        tc.ConstructionTable(re,"Ingreso","Aspirantes",aModel,DataTable );
                        break;
                case "Intensivo":
                        String queryString1 = 
                                     "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                                     + "SELECT ?Ingreso ?Aspirantes \n"
                                     + "WHERE { ?pum ont:ingresan_por ?are. \n"
                                     + "?pum ont:nombre ?Aspirantes.\n"
                                     + "?are ont:id ?Ingreso. \n"
                                     + "FILTER(?Ingreso = 2)}";
                        ResultSet re1 = OpenOWL.ExecSparQl(queryString1);
                        tc.ConstructionTable(re1,"Ingreso","Aspirantes",aModel,DataTable );
                        break;
                case "Regular":
                        String queryString2 = 
                                     "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                                     + "SELECT ?Ingreso ?Aspirantes \n"
                                     + "WHERE { ?pum ont:ingresan_por ?are. \n"
                                     + "?pum ont:nombre ?Aspirantes.\n"
                                     + "?are ont:id ?Ingreso. \n"
                                     + "FILTER(?Ingreso = 3)}";
                        ResultSet re2 = OpenOWL.ExecSparQl(queryString2);
                        tc.ConstructionTable(re2,"Ingreso","Aspirantes",aModel,DataTable );
                        break;    

                default: System.out.println("Selecciona una Universidad");;
                         break;
            }
            
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_comboINgresoActionPerformed

    private void btnTipoIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoIngresoActionPerformed
        // TODO add your handling code here:
        try{
            String[] tableColumnsName = {"Ingreso","Aspirantes"}; 
            DefaultTableModel aModel = (DefaultTableModel) DataTable.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            aModel.setRowCount(0);
            String queryString = 
                         "PREFIX ont: <http://www.semanticweb.org/rhyzard/ontologies/2021/2/untitled-ontology-13#> \n"
                         + "SELECT ?Ingreso ?Aspirantes \n"
                         + "WHERE { ?pum ont:ingresan_por ?are. \n"
                         + "?pum ont:nombre ?Aspirantes.\n"
                         + "?are ont:nombre ?Ingreso.}"; 
            ResultSet re = OpenOWL.ExecSparQl(queryString);
            tc.ConstructionTable(re,"Ingreso","Aspirantes",aModel,DataTable );
                    
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnTipoIngresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIngresoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIngresoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIngresoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIngresoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TIngresoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnpVolver;
    private javax.swing.JTable DataTable;
    private javax.swing.JButton btnTipoIngreso;
    private javax.swing.JComboBox<String> comboINgreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
